global:
  scrape_interval: 5s  # how often Prometheus scrapes metrics

scrape_configs:
  - job_name: 'request-service'
    static_configs:
      - targets: ['request-service:5002']

  - job_name: 'matching-service'
    static_configs:
      - targets: ['matching-service:5003']